name: CI Cloudfront S3 Bucket
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: RodDevOps/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete  --exclude '.git/*'

    steps:
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-east-1

    steps: 
      - name: Delete cache
        run: aws cloudfront create-invalidation --distribution-id E213E3BUMDTDNQ --paths "/*"
